package com.wycliffe.housingAgencyApplication;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Dimension;
import static java.awt.Frame.ICONIFIED;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wycliffe.Ochieng
 */
public final class Tenants extends javax.swing.JFrame {
    SimpleDateFormat dateFormat;
    String SQLTenantsRpt;
    ResultSet rsRpt;
    Statement stRpt;
    String filename = new SimpleDateFormat("yyyyMMddHHmm'.pdf'").format(new Date());
    String currency="Kes.", FileBaseName="Tenants", tenantStartDate, tenantEndDate;
    Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
    
    Connection con;
    ResultSet rs;
    Statement st;
    String SQLCustomers = "select * from customers";
    String customerID, firsName,lastName,idNumber,email,phone,phone2,nextOfKin,
            nextOfKinContact,apartmentId,houseNumber,rate,entyDate,ownerID,arrears;
    String startDate, endDate;
   
    int selectedRowIndex;
    int yMouse,xMouse;
    DefaultTableModel model;
    String [] ProductsArray;
    ArrayList<String> ProductsList;
    public static Tenants tenants =null; 
    public static Tenants getTenants(){
       
        if(tenants==null){
           tenants = new Tenants(); 
        }
         return tenants;
    }

    
    public void tenantsView(){
            try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/housing?autoReconnect=true&useSSL=true","root","prof1989*");
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery(SQLCustomers);
            model=(DefaultTableModel) jTableSendData.getModel();
 
            try{

                   while(rs.next())
                       {
                        customerID  = rs.getString("customer_id");
                        firsName = rs.getString("first_name");
                        lastName = rs.getString("last_name");
                        email = rs.getString("email");
                        phone = rs.getString("phone1");
                        phone2 = rs.getString("phone2");
                        nextOfKin  = rs.getString("next_of_kin");
                        nextOfKinContact = rs.getString("next_of_kin_phone");
                        apartmentId = rs.getString("apartment_id");
                        houseNumber = rs.getString("house_no");
                        rate = rs.getString("rate");
                        entyDate = rs.getString("entry_date");
                        ownerID = rs.getString("owner_id");
                        
                        
                        model.addRow(new Object[]
                        {customerID, firsName,lastName,email,phone,phone2,nextOfKin,nextOfKinContact,
                            apartmentId,houseNumber,rate,entyDate,ownerID
                        });
                       } 
                   }
                   catch(SQLException e){
                      
                   }
     }
    catch(SQLException e){
    }
    }
    
    public Tenants(){
        this.ProductsList = new ArrayList<>();
        initComponents();
        this.tenantsView();
    
    }
    //create object of the class AdminTenants
    AdminTenants showDataObject  = new AdminTenants();  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogDate = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonReportRequest = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldStartDate = new javax.swing.JTextField();
        jTextFieldEndDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSendData = new javax.swing.JTable();
        sidepane = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonOwners = new javax.swing.JButton();
        jButtonTenants = new javax.swing.JButton();
        jButtonHelp = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jButtonReport = new javax.swing.JButton();
        jButtonPayments = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonMin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonAddTenant = new javax.swing.JButton();

        jDialogDate.setMinimumSize(new java.awt.Dimension(376, 277));
        jDialogDate.setModal(true);
        jDialogDate.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDialogDate.setUndecorated(true);
        jDialogDate.setSize(new java.awt.Dimension(300, 300));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Please Enter Dates for the Report");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("From Date:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("To Date:");

        jButtonReportRequest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonReportRequest.setText("Submit");
        jButtonReportRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportRequestActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 0, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButtonReportRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButtonReportRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jDialogDateLayout = new javax.swing.GroupLayout(jDialogDate.getContentPane());
        jDialogDate.getContentPane().setLayout(jDialogDateLayout);
        jDialogDateLayout.setHorizontalGroup(
            jDialogDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogDateLayout.setVerticalGroup(
            jDialogDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jTableSendData.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTableSendData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustomerID", "First Name", "Last Name", "Email", "Phone Number", "Other Phone Number", "Next of Kin", "Contact of Next of Kin", "Apartment ID", "House Number", "House Rent", "Entry Date", "Owner A/C"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSendData.setMaximumSize(new java.awt.Dimension(2147483647, 800));
        jTableSendData.setRequestFocusEnabled(false);
        jTableSendData.setRowHeight(25);
        jTableSendData.getTableHeader().setReorderingAllowed(false);
        jTableSendData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSendDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSendData);
        if (jTableSendData.getColumnModel().getColumnCount() > 0) {
            jTableSendData.getColumnModel().getColumn(11).setPreferredWidth(120);
        }

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 5));

        jButtonOwners.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonOwners.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/icons/open.png"))); // NOI18N
        jButtonOwners.setText("View Owners");
        jButtonOwners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOwnersActionPerformed(evt);
            }
        });

        jButtonTenants.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTenants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/icons/Home.png"))); // NOI18N
        jButtonTenants.setText("Apartments");
        jButtonTenants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTenantsActionPerformed(evt);
            }
        });

        jButtonHelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/icons/Help.png"))); // NOI18N
        jButtonHelp.setText("Get Help     ");
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });

        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/icons/Brick_house.png"))); // NOI18N
        jButtonHome.setText("Return Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/icons/File PDF-01.png"))); // NOI18N
        jButtonReport.setText("Tenants Report");
        jButtonReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportActionPerformed(evt);
            }
        });

        jButtonPayments.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/icons/New Doc.png"))); // NOI18N
        jButtonPayments.setText("Payments    ");
        jButtonPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaymentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidepaneLayout = new javax.swing.GroupLayout(sidepane);
        sidepane.setLayout(sidepaneLayout);
        sidepaneLayout.setHorizontalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonHelp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPayments, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTenants, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOwners, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReport, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidepaneLayout.setVerticalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonOwners, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonTenants, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonReport)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        sidepaneLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonHelp, jButtonHome, jButtonPayments, jButtonReport, jButtonTenants});

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setBackground(new java.awt.Color(153, 0, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("_________ Tenants Details________");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystem/icons/Button Close-01.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });

        jButtonMin.setText("Minimize");
        jButtonMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(189, 189, 189)
                .addComponent(jButtonMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonMin)
                            .addComponent(jLabel1))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButtonAddTenant.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAddTenant.setText("Add Tenant");
        jButtonAddTenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTenantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddTenant, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddTenant, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1341, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableSendDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSendDataMouseClicked
        // called when the mouse is clicked.
        selectedRowIndex = jTableSendData.getSelectedRow();
      
        showDataObject.jtxtTenantID.setText(model.getValueAt(selectedRowIndex,0).toString());
        showDataObject.jtxtFirstName.setText(model.getValueAt(selectedRowIndex,1).toString());
        showDataObject.jtxtLastName.setText(model.getValueAt(selectedRowIndex,2).toString());
        showDataObject.jtxtEmail.setText(model.getValueAt(selectedRowIndex,3).toString());
        showDataObject.jtxtPhoneNumber.setText(model.getValueAt(selectedRowIndex,4).toString()); 
        showDataObject.jtxtAltPhone.setText(model.getValueAt(selectedRowIndex,5).toString()); 
        showDataObject.jtxtNextOfKin.setText(model.getValueAt(selectedRowIndex,6).toString());
        showDataObject.jtxtKinContact.setText(model.getValueAt(selectedRowIndex,7).toString());
        showDataObject.jtxtApartmentID.setText(model.getValueAt(selectedRowIndex,8).toString());
        showDataObject.jtxtHouseNum.setText(model.getValueAt(selectedRowIndex,9).toString());
        showDataObject.jtxtRentPayable.setText(model.getValueAt(selectedRowIndex,10).toString());
        showDataObject.jtxtHouseEntryDate.setText(model.getValueAt(selectedRowIndex,11).toString());
        showDataObject.jTextFieldOwnerID.setText(model.getValueAt(selectedRowIndex, 12).toString());
        
        
        showDataObject.jbtnSave.setEnabled(false);
        showDataObject.jtxtApartmentID.setEditable(false);
        this.dispose();
        showDataObject.setAlwaysOnTop(true);
        showDataObject.jbtnSave.setEnabled(false);
        showDataObject.setVisible(true);
        showDataObject.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        showDataObject.pack();
        
        
        
                
    }//GEN-LAST:event_jTableSendDataMouseClicked

    private void jButtonOwnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOwnersActionPerformed
        // call owners form
        Owners.getOwners().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonOwnersActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // call Home form
        Home.getHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportActionPerformed
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - jDialogDate.getWidth()) / 2;
        final int y = (screenSize.height - jDialogDate.getHeight()) / 2;
        jDialogDate.setLocation(x, y);
        jDialogDate.setUndecorated(true);
        jDialogDate.setVisible(true);
        
        //make sure no null is allowed
        
    }//GEN-LAST:event_jButtonReportActionPerformed

    private void jButtonAddTenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTenantActionPerformed
        // call Edit tenants form
        AdminTenants.getAdminTenants().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonAddTenantActionPerformed

    private void jButtonTenantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTenantsActionPerformed
        // call all Tenants Form
        Apartments.getApartment().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonTenantsActionPerformed

    private void jButtonPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaymentsActionPerformed

        Payments.getPayements().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPaymentsActionPerformed

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
       Home.getHome().setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_jLabel1KeyPressed

    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
        // TODO add your handling code here:
                new HousingAgencyHelp().setVisible(true);
    }//GEN-LAST:event_jButtonHelpActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       // TODO add your handling code here:
       Home.getHome().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButtonReportRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportRequestActionPerformed
        // retrieves data from the date chooser;
        startDate  = jTextFieldStartDate.getText();
        endDate = jTextFieldEndDate.getText();
        
        if(jTextFieldStartDate.getText().isEmpty()){
             
            JOptionPane.showConfirmDialog(null,"Incorect Date Entered. Please check and try again" , "Tenants Report",JOptionPane.INFORMATION_MESSAGE);
            jTextFieldStartDate.requestFocusInWindow();
            jTextFieldStartDate.grabFocus();
        }
        if(jTextFieldEndDate.getText().isEmpty()){
             
            JOptionPane.showConfirmDialog(null,"Incorect Date Entered. Please check and try again" , "Tenants Report",JOptionPane.INFORMATION_MESSAGE);
            jTextFieldEndDate.requestFocusInWindow();
            jTextFieldEndDate.grabFocus();
        }
        else
        {
        java.sql.Date sqlStartDate = java.sql.Date.valueOf(startDate);
        java.sql.Date stqlEndDate = java.sql.Date.valueOf(endDate);
        
        System.out.println("startDate"+sqlStartDate);
        System.out.println("endDate"+stqlEndDate);
        try{
        
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/housing?useSSL=true","root","prof1989*");
        stRpt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        
        SQLTenantsRpt = "select * from customers where date(entry_date) between '"+sqlStartDate+"' and '"+stqlEndDate+"'";
        rsRpt = stRpt.executeQuery(SQLTenantsRpt);
        
        ResultSetMetaData rsmd = rsRpt.getMetaData();
        int columnCount = rsmd.getColumnCount();
        rsRpt.first();
        Document pdf = new Document(PageSize.A4.rotate());
        
        PdfWriter.getInstance(pdf,new FileOutputStream("E:\\prof\\"+FileBaseName+filename));
        
        Image img = Image.getInstance("E:\\Wycliffe\\Apps\\JAVA_Projects\\HousingAgencyApp\\src\\payrollsystem\\brighter5.JPG");
        img.setWidthPercentage(100);
        img.scaleToFit(770f, 112f);
        
        
        PdfPTable printTable = new PdfPTable(11);
        printTable.setWidthPercentage(100);
        Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);

            printTable.addCell("Customer ID");
            printTable.addCell("First Name");
            printTable.addCell("Last Name");
            //printTable.addCell("National ID");
            //printTable.addCell("E-mail");
            printTable.addCell("Phone No:");
            //printTable.addCell("Other Phone NO:");
            printTable.addCell("Next Of Kin");
           // printTable.addCell("Kin's Contact");
            printTable.addCell("Apartment ID");
            printTable.addCell("House Number");
            printTable.addCell("Rent Payable");
            printTable.addCell("Entry Date");
            printTable.addCell("Total Arrears");
            printTable.addCell("Owner A/C");
            
            printTable.setHeaderRows(1);
            pdf.open();
        
            System.out.println(columnCount);
            pdf.open();
            Paragraph pg =new Paragraph("",boldFont);
            Date date =new Date();
            String sDate = date.toString();
            pg.add("Tenants Report"+"\n"+sDate+"\n");
            pg.setAlignment(Element.ALIGN_CENTER);
            pg.add(" ");
            pdf.add(pg);
            
            Paragraph pgLogo =new Paragraph("",boldFont);//Start of second paragraph
            pgLogo.setAlignment(Element.ALIGN_CENTER);
            pgLogo.add(img);
            pgLogo.add(" ");
            pdf.add(pgLogo);//End of second paragraph
            
        if(rsRpt!=null){
          do{
                    printTable.addCell(rsRpt.getString("customer_id"));
                    printTable.addCell(rsRpt.getString("first_name"));
                    printTable.addCell(rsRpt.getString("last_name"));
                    //printTable.addCell(rsRpt.getString("id_no"));
                    //printTable.addCell(rsRpt.getString("email"));
                    printTable.addCell(rsRpt.getString("phone1"));
                    //printTable.addCell(rsRpt.getString("phone2"));
                    printTable.addCell(rsRpt.getString("next_of_kin"));
                    //printTable.addCell(rsRpt.getString("next_of_kin_phone"));              
                    printTable.addCell(rsRpt.getString("apartment_id"));
                    printTable.addCell(rsRpt.getString("house_no"));
                    printTable.addCell(currency+rsRpt.getString("rate"));
                    printTable.addCell(rsRpt.getString("entry_date"));
                    printTable.addCell(currency+rsRpt.getString("Total_Arrears"));
                    printTable.addCell(rsRpt.getString("owner_id"));
        }
        while(rsRpt.next());
        pdf.add(printTable);
        
        Font boldFont1 = new Font(Font.FontFamily.TIMES_ROMAN, 13, Font.BOLD);
        Paragraph pgCom =new Paragraph("",boldFont1);
        pgCom.add(" ");
        pgCom.add("Prepared By : Isaac Watari Ngigi on: "+sDate+"\n"); 		
        pgCom.add("");
        pgCom.add("___________________________________________________________________________");
        pgCom.add("___________________________________________________________________________");
        pgCom.setAlignment(Element.ALIGN_BOTTOM);
        pdf.add(pgCom);//add third paragraph
        pdf.close();
        
        if(Desktop.isDesktopSupported()){
            
           File report = new File("E:/prof/"+FileBaseName+filename);
            Desktop.getDesktop().open(report);
        }
        else{
           JOptionPane.showMessageDialog(null, "No application installed to support file.\n"+"Please install PDF reader","Tenant's  Details",JOptionPane.INFORMATION_MESSAGE);   
        }      
        }
        else{
             JOptionPane.showMessageDialog(null, "No Records Exist between the specified Dates.\n"+"Please specify other dates","Tenant's  Details",JOptionPane.INFORMATION_MESSAGE);   
        }
        }

    catch(SQLException ex){
         Logger.getLogger(Tenants.class.getName()).log(Level.SEVERE, null, ex);
    }   catch (FileNotFoundException ex) {
            Logger.getLogger(Tenants.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException | IOException ex) {
            Logger.getLogger(Tenants.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tenants.class.getName()).log(Level.SEVERE, null, ex);
        }

        jDialogDate.dispose();//close the dialog box and then show the parent form.
       Tenants.getTenants().setVisible(true);
     }
    }//GEN-LAST:event_jButtonReportRequestActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xMouse, y-yMouse);

    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jButtonMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinActionPerformed
        // TODO add your handling code here:
        setState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinActionPerformed

//Instance of the main method...
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new Tenants().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAddTenant;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonMin;
    private javax.swing.JButton jButtonOwners;
    private javax.swing.JButton jButtonPayments;
    private javax.swing.JButton jButtonReport;
    private javax.swing.JButton jButtonReportRequest;
    private javax.swing.JButton jButtonTenants;
    private javax.swing.JDialog jDialogDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable jTableSendData;
    private javax.swing.JTextField jTextFieldEndDate;
    private javax.swing.JTextField jTextFieldStartDate;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
